### ISSUE TITLE
Emoji

### ISSUE THREAD

**Issue by damdamo** [kyouko-taiga/FunBlocks#7]
Je ne sais pas si c'est possible, mais il serait agréable que les termes supportent unicodes, pour mettre des emojis dans les identifiants des termes.

**Comment by kyouko-taiga** [comment]
C'est malheureusement très compliqué pour le parser. Il suffit de voir [les règles syntaxiques de Swift](https://docs.swift.org/swift-book/ReferenceManual/zzSummaryOfTheGrammar.html) qui définissent un identifiant.
